name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8
      - name: Build project
        run: mvn -B install --file pom.xml
      - name: Build example 1
        run: mvn -B package --file examples/jetty-webhook-echobot/pom.xml
      - name: Build example 2
        run: mvn -B package --file examples/longpolling-echobot/pom.xml
      - name: Build example 3
        run: mvn -B package --file examples/tomcat-webhook-echobot/pom.xml
